# Generated by Django 2.1.5 on 2019-01-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_coinpayments', '0002_auto_20180428_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpaymentstransaction',
            name='dest_tag',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Payment ID'),
        ),
    ]
